{"number": 2600, "ref": "fix-async-from-sync-close", "login": "mhofman", "head": "1937798149243e406b644cd7289bbdaa7980ac13", "base": "012af13cb8d7ba78a3125086a2cd9059a1f8a4e8", "title": "Normative: Close sync iterator when async wrapper yields rejection", "created_at": "2021-12-17T02:56:25Z", "updated_at": "2021-12-17T04:38:39Z", "revs": [{"hash": "1937798149243e406b644cd7289bbdaa7980ac13", "parents": "92262e309fe9492c6f8e0134ff3568ea1e75538b", "author": "Mathieu Hofman", "date": "2021-12-17T04:37:56+00:00", "adate": "2021-12-17T04:37:56+00:00", "subject": "fix: do not close a done iterator"}, {"hash": "92262e309fe9492c6f8e0134ff3568ea1e75538b", "parents": "012af13cb8d7ba78a3125086a2cd9059a1f8a4e8", "author": "Mathieu Hofman", "date": "2021-12-17T03:06:44+00:00", "adate": "2021-12-17T02:22:37+00:00", "subject": "Normative: Close sync iterator when async wrapper yields rejection"}]}